// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WalletService.Persistence;

#nullable disable

namespace WalletService.Persistence.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20250613081806_MigrateToPostgres")]
    partial class MigrateToPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "1.1.1-servicing")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WalletService.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccountId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("WalletService.Domain.Entities.BonusAccount", b =>
                {
                    b.Property<Guid>("BonusAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("BonusAccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BonusAccountId");

                    b.ToTable("BonusAccount", (string)null);
                });

            modelBuilder.Entity("WalletService.Domain.Entities.BonusWalletTransaction", b =>
                {
                    b.Property<long>("BonusWalletTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BonusWalletTransactionId"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Credit")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("DateExpired")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateStarted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ModeOfTransaction")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("PreviousBalance")
                        .HasColumnType("numeric");

                    b.Property<long>("PromotionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionNo")
                        .HasColumnType("text");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("text");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.HasKey("BonusWalletTransactionId");

                    b.HasIndex("AccountId");

                    b.ToTable("BonusWalletTransaction", (string)null);
                });

            modelBuilder.Entity("WalletService.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<long>("WalletTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WalletTransactionId"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Credit")
                        .HasColumnType("numeric");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ModeOfTransaction")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("PreviousBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionNo")
                        .HasColumnType("text");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("text");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.HasKey("WalletTransactionId");

                    b.HasIndex("AccountId");

                    b.ToTable("WalletTransaction", (string)null);
                });

            modelBuilder.Entity("WalletService.Domain.Entities.BonusWalletTransaction", b =>
                {
                    b.HasOne("WalletService.Domain.Entities.BonusAccount", "BonusAccount")
                        .WithMany("BonusWalletTransactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonusAccount");
                });

            modelBuilder.Entity("WalletService.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("WalletService.Domain.Entities.Account", "Account")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("WalletService.Domain.Entities.Account", b =>
                {
                    b.Navigation("WalletTransactions");
                });

            modelBuilder.Entity("WalletService.Domain.Entities.BonusAccount", b =>
                {
                    b.Navigation("BonusWalletTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
